language: php

sudo: false
dist: trusty

git:
  depth: 3

notifications:
  email: false
  slack:
    secure: k23wSAJ6NzLU2O/DvstKfZfuf2KzoGWG5wn2AKE0/IFpdwAyR1UFadiIz4v2CzOnQIG7uLeNIsG8wzG2iMXuVMy77evsF5vdGfN1HfFVLmmZBsuVXgfRWr0PWbGP3S7cZBbJoQdLxqFMRP6MZGb27T4vgoCNIsD7aYXu9vXWtDJmi/gJb0ToAsejfj1UV9BA4YX9JoFS4LXrFx7REmbwJQCelFUevz3NVgdotfZlo/VFenCrYg8KNjgocd9b7SeZf6B4I1C42D+sBOfz6kGTYPt6rMZ8RD1Nzcmc2miWSca64APKJpcxXVdtgztjz92xFfYfaPcT9JH8vAl2TjR4dqWEDzs/6rsUyCiXkmEwluV+x9ygfbdaEHd1EGneQ8zNa761xsjvzGaS6OysSSOU/QKy8ummr8vczX0q4Iv8WO4fKxlxmOORxhm5ri3QAVLhltwLXbuCw9WF5Y87vpFxd+C6pG7U4/uIxv5ZEOhJdj7effk2p9kgO6b9IC/S3bd3LneGMkhMvLffObsQeqN+8D86FTG7O7hr9SJcrHKiNcHkAyokJGXBl5mmEDqULOHsNMekSCRADUn8nuWbWLsg28NzQelIZd4Uf46wuzvUXk0vrmjY2Ro1lnGk6upwwUUV64uh8pPgcLqTfPZGW3zsTY4bx/tNwCQELCQ20YxUsu0=

branches:
  only:
    - master
    - "/^v[0-9\\.]+/"

cache:
  yarn: true
  directories:
    - "${HOME}/.composer/cache"
    - node_modules
    - "${TRAVIS_BUILD_DIR}/.plugin"
    - "${TRAVIS_BUILD_DIR}/.work/cache"

addons:
  apt:
    packages:
      - unar

stages:
  - name: check
    if: branch = master and tag IS blank and type IN (pull_request, api, cron)
  - name: test
    if: branch = master and tag IS blank and type IN (pull_request, api)
  - name: test trunk
    if: branch = master and tag IS blank and type IN (pull_request, api, cron)
  - name: deploy
    if: tag IS present

before_install:
  - npm install -g npm@latest
  - npm install -g yarn@latest

before_script:
  - git clone --depth=1 https://github.com/wp-content-framework/travis-ci.git travis-ci
  - bash travis-ci/bin/prepare.sh

jobs:
  fast_finish: true
  include:
    - stage: check
      language: php
      php: '7.2'
      script: bash travis-ci/bin/php/phpcs.sh
    - stage: check
      language: php
      php: '7.2'
      script: bash travis-ci/bin/php/phpmd.sh

    - stage: check
      language: node_js
      node_js: '11'
      dist: trusty
      script: bash travis-ci/bin/js/js-lint.sh


    - stage: test
      language: php
      php: '7.3'
      env:
        - WP_VERSION=latest
        - WP_MULTISITE=1
        - COVERAGE_REPORT=1
        - ACTIVATE_POPULAR_PLUGINS=1
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.2'
      env:
        - WP_VERSION=5.2
        - WP_MULTISITE=1
        - COVERAGE_REPORT=1
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.0'
      env:
        - WP_VERSION=5.0
        - COVERAGE_REPORT=1
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '5.6'
      env:
        - WP_VERSION=latest
        - COVERAGE_REPORT=1
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '5.6'
      env:
        - WP_VERSION=5.0
        - WP_MULTISITE=1
        - COVERAGE_REPORT=1
      script: bash travis-ci/bin/php/wp-test.sh

    - stage: test
      language: node_js
      node_js: '11'
      dist: trusty
      env: COVERAGE_REPORT=1
      script: bash travis-ci/bin/js/js-test.sh


    - stage: test trunk
      language: php
      php: '7.3'
      env:
        - WP_VERSION=trunk
        - WP_MULTISITE=1
        - ACTIVATE_POPULAR_PLUGINS=1
      script: bash travis-ci/bin/php/wp-test.sh

    - stage: test trunk
      language: php
      php: '5.6'
      env: WP_VERSION=trunk
      script: bash travis-ci/bin/php/wp-test.sh


    - stage: deploy
      language: node_js
      node_js: '11'
      dist: trusty
      script: skip
      before_deploy:
        - source travis-ci/bin/deploy/env.sh
        - bash travis-ci/bin/deploy/create.sh
      deploy:
        provider: releases
        skip_cleanup: true
        name: ${RELEASE_TITLE}
        tag_name: ${RELEASE_TAG}
        api_key:
          secure: SED2xsuudQql6XDDhUXESghmbqzuOrxKMMM/jdRBSkj4IBkUkmq+273uiFeZKdNau/CgM4uqaFus2LFcGyJdLkA+HlO1aP+1yDMzCKoMVRuDRk4foo3/EiS21hYX4RmHLzERSlM9EKjfH1GN37v01LqIV+59NmSwiRBMXkIOaeGC3lVXeT6oeUnCvPfQjTc9Da24mCObHwPqgfWIjw4SaA4WGT+aEvjv9xLZst8c68/P/wz77eZsrgJMxcXKn/zr/OrlYUeQdPhSQLLU2BSI4BoSqPxI6EjQz6W7NumRHyTm0b7D6y5C9SyvaC8A7+iibdC5xWGxfHGORaA3ix8T+ihCnK/dDSelcUAjxB/Cp1T3BJCTCW1fnqRR1g86ddulzy2oJBhuGyxHkWcmTR34tp59bTIA6WkEAXPg9TNOs5LALDXK3scy+pQ4u+wu3yxyGVJon6su/0j1r77WEt9O0Ob6UqeYtQ+CHynU4Ix2xzH7jgYfPBCJIIVm4MPGiXQVW+YoRPNGGsreNe2rvVW3FrA3KoBZvPI2RI44jx2Zf1SIMPEVi5zSgqEhoZMnpXrxedphOvJ86EgrByfd9vr3b9rW4/qXZy2f3Kjt41XVou3fqbR0vrbTbClzXwqHzVssV+59S/nB//9ACfHYBZQrURR0N00060gLoFyzEz37Kcc=
        file: ${RELEASE_FILE}
        overwrite: true
        on:
          tags: true

    - stage: deploy
      language: node_js
      node_js: '11'
      dist: trusty
      env:
        - GH_PAGES_APP_ID=editor
        - GH_PAGES_PLUGIN_SCRIPT="./index.min.js"
        - GH_PAGES_PLUGIN_STYLE="./index.css"
        - GH_PAGES_TITLE="Marker Animation"
        - GH_PAGES_TEMPLATE=gutenberg
        - GH_PAGES_TRACKING_ID=UA-78163306-3
      script: skip
      before_deploy:
        - source travis-ci/bin/deploy/env.sh
        - bash travis-ci/bin/deploy/gh-pages.sh
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: ${GITHUB_TOKEN}
        keep_history: true
        local_dir: ${GH_PAGES_DIR}
        on:
          tags: true
